nodes:
- host: localhost
  id: node1
  memory_limit: 512MB
  port: 6379
  role: primary
- host: localhost
  id: node2
  memory_limit: 512MB
  port: 6380
  role: replica
- host: localhost
  id: node3
  memory_limit: 512MB
  port: 6381
  role: replica
settings:
  chunk_size: 1048576
  heartbeat_interval: 30
  quorum:
    N: 3
    R: 2
    W: 2
  redis_insight:
    enabled: true
    port: 8001
    read_only: true
  replication_factor: 2
  stability:
    base_backoff: 5
    grace_period: 60
    max_reconnect_attempts: 5
    min_election_interval: 2
